# Generated by Django 4.2.11 on 2024-03-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('departamento', 'Departamento')], max_length=50)),
                ('num_bedrooms', models.PositiveSmallIntegerField()),
                ('price_min', models.PositiveIntegerField()),
                ('price_max', models.PositiveIntegerField()),
            ],
        ),
    ]
